[package]
name = "blawgd-solana"
version = "0.1.0"
edition = "2018"

[dependencies]
solana-program = "1.14.10"
borsh = "0.9.3"

[dev-dependencies]
solana-sdk = "1.14.10"
solana-client = "1.14.10"
solana-program-test = "1.14.10"


[lib]
crate-type = ["cdylib", "lib"]
